# Language is R
language: r

# R versions
r:
  - oldrel
  - release

# Operating systems to build on ------
os:
  - linux
  - osx

# Linux options ---------
sudo: false
dist: trusty
cache: packages

# If anyone else would like to be added to notifications,
# just add your email below!
notifications:
  email:
    - jonesor@gmail.com
    - levisc8@gmail.com

# add additional Github packages
r_github_packages:
- jonesor/Rcompadre
